### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'docker --version'

### ISSUE THREAD

**Issue by SOMLpj** [SCE-Development/dev#7]
When I was running set up I got this error. I believe it is due to this line. 
[setup.py; line 26](https://github.com/SCE-Development/dev/blob/bea3cab84a2819f9b811fc7f769828444340f49b/tools/setup.py#L26)

**Comment by evanugarte** [comment]
Seems like the error is thrown when a command isnt found (e.g. i didnt have mongo):
![image](https://user-images.githubusercontent.com/36345325/87213258-95319300-c2d8-11ea-96c5-be07727d4781.png)

**Comment by evanugarte** [comment]
haha here's da answer:
![image](https://user-images.githubusercontent.com/36345325/87213324-f48fa300-c2d8-11ea-9a73-f764b7496bee.png)
